### PR TITLE
refactor: update retrofit example, check it works

### PR DESCRIPTION
**Pull request by jean-philippe-martin**
Also, rename the folder to leave room for upcoming (actual) examples.

Also, fix the link to google-cloud-examples.

I had to change the pom a bit so google-cloud-nio-retrofit would build by default, please take a look. 

Running the retrofit example:

```
$ mvn package
(...)
$ java -cp google-cloud-nio/target/google-cloud-nio-0.120.1-alpha-SNAPSHOT-shaded.jar:google-cloud-nio-retrofit/target/google-cloud-nio-retrofit-0.120.1-alpha-SNAPSHOT.jar com.google.cloud.nio.retrofit.ListFilesystems
Installed filesystem providers:
  file
  jar
  gs
$ java -cp google-cloud-nio-retrofit/target/google-cloud-nio-retrofit-0.120.1-alpha-SNAPSHOT.jar com.google.cloud.nio.retrofit.ListFilesystems
Installed filesystem providers:
  file
  jar
```

### CODE REVIEW

**Comment by jean-philippe-martin** [comment]
I see some integration tests failing for things I didn't change. Looks like we may need to do a bit of configuration work still for the integration tests.

**Comment by chingor13** [comment]
@jean-philippe-martin I opened #8 for the integration test failures. I think this broke when we started running our tests on Kokoro (from Circle CI a year+ ago, but we weren't running the integration tests for google-cloud-nio in the monorepo). Our Kokoro runners run on a GCE instances which will detect a default project id from the metadata server.

For the code format test, try running `mvn com.coveo:fmt-maven-plugin:format` to lint the code.

**Comment by jean-philippe-martin** [comment]
Format updated.

Yes, some of the integration tests require a specific configuration and that's probably what's tripping it. We'll probably need a very specific script to drive the test and move the configuration in between. I believe we can set some environment variables to override GCE's defaults.

**Comment by jean-philippe-martin** [comment]
Thank you!

**Pull request merged**
