### PR TITLE
test: update FakeStorageRpc to extend StorageRpcTestBase

### LINKED ISSUE #124: test: update FakeStorageRpc to extend StorageRpcTestBase
Now FakeStorageRpc implements the StorageRpc interface from the Storage module.
This makes it impossible to extend the StorageRpc because it breaks cross-module dependencies.

Updating `FakeStorageRpc` to extend newly introduce `StorageRpcTestBase` as suggested in 
https://github.com/googleapis/java-storage/issues/242 will help.

### PR DESCRIPTION
**Pull request by dmitry-fa**
Fixes #124

### CODE REVIEW

**Comment by dmitry-fa** [comment]
@frankyn, @chingor13, @JesseLovelace 
I added a new class in java-storage 1.109.0 and try to use this class in java-storage-nio.
Everything is fine, but linkage-monitor check fails: the new class is not found. Looks like the linkage-monitor refers to an outdated version of java-storage.
Could you give me any advice on how to handle this?

**Comment by frankyn** [comment]
Hi @dmitry-fa, thanks for putting this together. I merged the updated version of Java-storage. Please merge master into your branch.

**Comment by frankyn** [comment]
@kolea2 could you help release a new version of libraries-bom with updated versions of google-cloud-storage and google-cloud-nio? It will help unblock this PR.

**Comment by frankyn** [comment]
Merge master @dmitry-fa

**Pull request merged**
